---
# title: "Отчет"
# subtitle: "Пример для КЦ"
format: 
  typst: 
    template-partials: 
      - typst-show.typ
      - typst-template.typ
    # логотип не вставляется
    #logo: logo_light.png
lang: ru
author: "Автор отчета"
params:
  species: Chinstrap

# дата отображается не в том формате, как требуется 
# нужно расширение now
# https://pkg.garrickadenbuie.com/quarto-now/
#date: today
# **{{< meta params.species >}}**
---

Текст создан {{< modified "%d %B %Y" >}} года. 

Рассматриваемый вид: **`r params$species`**.

```{r}
#| echo: false
#| warning: false
#| fig-width: 8
#| fig-height: 4

# коллекция библиотек tidyverse 📦
library(tidyverse)

# библиотека с данными
library(palmerpenguins)

gg_highlight <- 
penguins |> 
  #filter(species == "Adelie") |>
  na.omit() |>
  ggplot(aes(x = flipper_length_mm, 
             fill = species)) + 
  geom_bar() +
  silgelib::theme_roboto(base_size = 14) +
  ggsci::scale_fill_nejm(alpha = 0.9) +
  scale_x_continuous(name = "Размах плавника",
                     labels = function(x) str_c(x, " мм")) +
  labs(y = "количество", fill = "вид") +
  theme(
    base_size = 13,
    axis.line = element_line(),
    panel.grid.major = element_line("grey95", 
                                    linewidth = 0.3),
    plot.margin = ggplot2::margin(t = 0.5,
                                  r = 0.5, 
                                  b = 0.5, 
                                  l = 0.5, "cm")
  )

library(gghighlight)

gg_highlight +
  gghighlight(species == params$species) +
  facet_wrap(~species)
```

```{r}
#| echo: false
#| warning: false
#| tbl-label: Penguins-tbl
#| tbl-cap: "Пример параметризации в таблице"
#| tbl-cap-location: top
# library(gt)
library(tinytable)
options(tinytable_latex_placement = "H")

penguins |> 
  #filter(species == "Adelie") |>
  na.omit() |>
  filter(species == params$species) |>
  mutate(body_mass = body_mass_g / 1000) |>
  rename("вид" = species,
         "длина клюва, мм" = bill_length_mm,
         "размах крыла, мм" = flipper_length_mm,
         "масса, кг" = body_mass,
         "пол" = sex) |>
  select(-year, -island, -bill_depth_mm, -body_mass_g) |>
  relocate(where(is.numeric), .before = last_col()) |>
  head(3) |> tt(width = c(1,1,1.5,1.5,1))  |>
  style_tt(fontsize = 0.9) 
  # style_tt(
  #   i = 1:3,
  #   j = 1,
  #   background = "teal",
  #   color = "white"
  # )
  # gt() |>
  # opt_table_font(font = "Times New Roman")
```

::: {.callout-warning title="Важно"}
Здесь будет текст, на который следует обратить внимание.
:::

Текст...

`r lorem::ipsum(paragraphs = 1, sentences = c(3))`





